import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as T from '../dist/vendor/three.module.js';
const data=JSON.parse(await readFile(new URL('../dist/scene-v412.json',import.meta.url),'utf8'));
const info=JSON.parse(await readFile(new URL('../dist/home102-viewer/assets/model-info.json',import.meta.url),'utf8'));
const bytes=await readFile(new URL('../dist/home102-viewer/assets/house-stable-v412.glb',import.meta.url));
const gltf=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());
const parents=new Map();gltf.nodes.forEach((n,i)=>(n.children||[]).forEach(c=>parents.set(c,i)));
const matrices=new Map();function world(i){if(matrices.has(i))return matrices.get(i);const n=gltf.nodes[i];const m=n.matrix?new T.Matrix4().fromArray(n.matrix):new T.Matrix4().compose(new T.Vector3(...(n.translation||[0,0,0])),new T.Quaternion(...(n.rotation||[0,0,0,1])),new T.Vector3(...(n.scale||[1,1,1])));if(parents.has(i))m.premultiply(world(parents.get(i)));matrices.set(i,m);return m;}
const byId=new Map(gltf.nodes.map((n,i)=>[n.extras?.pascalId,i]).filter(([id])=>id));
const of=type=>Object.values(data.nodes).filter(n=>n.type===type&&n.visible!==false);
const close=(actual,expected,label)=>assert.ok(Math.abs(actual-expected)<.0005,`${label}: ${actual} vs ${expected}`);
function corners(i){const n=gltf.nodes[i],mesh=gltf.meshes[n.mesh],points=[];if(!mesh)return points;for(const p of mesh.primitives){const a=gltf.accessors[p.attributes.POSITION];for(const x of [a.min[0],a.max[0]])for(const y of [a.min[1],a.max[1]])for(const z of [a.min[2],a.max[2]])points.push(new T.Vector3(x,y,z).applyMatrix4(world(i)));}return points;}
test('measurement metadata and GLB use the exact same Blender source',()=>{assert.equal(data.meta.version,412);assert.equal(data.meta.sourceSha256,info.sha256);assert.match(info.source,/STABLE_v412/);});
test('all 27 stable opening IDs and 19 columns exist in the GLB',()=>{assert.equal(of('door').length,9);assert.equal(of('window').length,18);assert.equal(of('column').length,19);for(const n of [...of('door'),...of('window'),...of('column')])assert.ok(byId.has(n.id),n.id);});
test('opening dimensions and levels match independently read GLB outer frame geometry',()=>{for(const o of [...of('door'),...of('window')]){const n=gltf.nodes[byId.get(o.id)];let frames=(n.children||[]).filter(i=>gltf.nodes[i].name.startsWith('Mesh_')&&gltf.nodes[i].mesh!==undefined);if(!frames.length)frames=(n.children||[]).filter(i=>gltf.nodes[i].mesh!==undefined);const points=frames.flatMap(corners);assert.ok(points.length,o.id);const inverse=world(byId.get(o.wallId)).clone().invert();const xs=points.map(p=>p.clone().applyMatrix4(inverse).x);const ys=points.map(p=>p.y);close(o.width,Math.max(...xs)-Math.min(...xs),o.id+' width');close(o.height,Math.max(...ys)-Math.min(...ys),o.id+' height');close(o.position[0],(Math.min(...xs)+Math.max(...xs))/2,o.id+' offset');close(o.position[1]-o.height/2,Math.min(...ys)-data.meta.floorDatum,o.id+' sill');}});
test('column dimensions and base levels match GLB geometry including extension to ground',()=>{for(const c of of('column')){const points=(gltf.nodes[byId.get(c.id)].children||[]).flatMap(corners);const box=new T.Box3().setFromPoints(points),size=box.getSize(new T.Vector3());close(c.height,size.y,c.id+' height');close(c.width,size.x,c.id+' width');close(c.depth,size.z,c.id+' depth');close(c.position[1],box.min.y-data.meta.floorDatum,c.id+' base');}});
test('opening codes keep the prior site ordering and dimensions sum to the wall axis',async()=>{const old=JSON.parse(await readFile(new URL('../dist/old-version/scene.json',import.meta.url),'utf8'));for(const type of ['door','window'])assert.deepEqual(of(type).map(o=>o.id),Object.values(old.nodes).filter(n=>n.type===type&&n.visible!==false).map(n=>n.id));for(const o of [...of('door'),...of('window')]){const w=data.nodes[o.wallId],length=Math.hypot(w.end[0]-w.start[0],w.end[1]-w.start[1]),left=o.position[0]-o.width/2,right=length-o.position[0]-o.width/2;close(left+o.width+right,length,o.id+' chain');}});
